workflows:
  ios-testflight-release:
    name: iOS TestFlight Release
    max_build_duration: 120
    environment:
      xcode: latest
      cocoapods: default
      node: 20.11.0
      vars:
        BUNDLE_ID: "com.cubstechnical.employee"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        APP_STORE_APP_ID: "6752909710"  # Your actual App Store Connect App ID
    integrations:
      app_store_connect: appstorekey
    scripts:
      - name: Install Node.js dependencies
        script: |
          echo "📦 Installing Node.js dependencies..."
          npm ci
      - name: Build Next.js app
        script: |
          echo "🏗️ Building Next.js production app..."
          npm run build
      - name: Sync Capacitor iOS
        script: |
          echo "🔄 Syncing web assets with Capacitor iOS..."
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          echo "📱 Installing CocoaPods dependencies..."
          cd ios/App
          pod install
          cd ../..
      - name: Set build number
        script: |
          echo "🔢 Setting build number..."
          cd ios/App
          # Get latest build number from App Store Connect and increment
          LATEST_BUILD=$(agvtool what-version -terse)
          NEW_BUILD=$((LATEST_BUILD + 1))
          echo "Setting build number to: $NEW_BUILD"
          agvtool new-version -all $NEW_BUILD
          cd ../..
      - name: Configure code signing
        script: |
          echo "🔐 Configuring code signing..."
          # Set up code signing environment
          export DEVELOPER_DIR="/Applications/Xcode.app/Contents/Developer"
          # Ensure proper code signing configuration
          cd ios/App
          # Force automatic signing in project file
          sed -i '' 's/CODE_SIGN_STYLE = Manual;/CODE_SIGN_STYLE = Automatic;/g' project.pbxproj
          sed -i '' 's/CODE_SIGN_IDENTITY = "iPhone Developer";/CODE_SIGN_IDENTITY = "";/g' project.pbxproj
          sed -i '' 's/CODE_SIGN_IDENTITY = "iPhone Distribution";/CODE_SIGN_IDENTITY = "";/g' project.pbxproj
          # Remove any manual provisioning profile settings
          sed -i '' '/PROVISIONING_PROFILE/d' project.pbxproj
          sed -i '' '/PROVISIONING_PROFILE_SPECIFIER/d' project.pbxproj
          echo "Code signing configuration updated for automatic signing"
          cd ../..
      - name: Use provisioning profiles
        script: |
          echo "🔐 Using provisioning profiles..."
          xcode-project use-profiles
      - name: Verify code signing configuration
        script: |
          echo "🔍 Verifying code signing configuration..."
          cd ios/App
          echo "Checking project code signing settings:"
          grep -n "CODE_SIGN_STYLE" project.pbxproj || echo "No CODE_SIGN_STYLE found"
          grep -n "CODE_SIGN_IDENTITY" project.pbxproj || echo "No CODE_SIGN_IDENTITY found"
          grep -n "PROVISIONING_PROFILE" project.pbxproj || echo "No PROVISIONING_PROFILE found"
          cd ../..
      - name: Prepare build directory
        script: |
          echo "📁 Preparing build directory..."
          mkdir -p build/ios/ipa
          mkdir -p build/ios/archive
          # Clean previous builds
          rm -rf build/ios/ipa/*.ipa
          rm -rf build/ios/archive/*.xcarchive
      - name: Create ExportOptions.plist
        script: |
          echo "📄 Creating ExportOptions.plist..."
          cat > ios/App/ExportOptions.plist << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <true/>
              <key>compileBitcode</key>
              <false/>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>thinning</key>
              <string>&lt;none&gt;</string>
              <key>destination</key>
              <string>export</string>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>signingCertificate</key>
              <string>Apple Distribution</string>
          </dict>
          </plist>
          EOF
          echo "ExportOptions.plist created successfully"
      - name: Build and archive iOS app
        script: |
          echo "🏗️ Building and archiving iOS app..."
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --archive-xcargs "CODE_SIGN_STYLE=Automatic CODE_SIGN_IDENTITY= PROVISIONING_PROFILE= PROVISIONING_PROFILE_SPECIFIER=" \
            --export-options-plist ios/App/ExportOptions.plist
      - name: Verify build artifacts
        script: |
          echo "✅ Verifying build artifacts..."
          if [ -d "build/ios/ipa" ] && [ "$(ls -A build/ios/ipa/*.ipa 2>/dev/null)" ]; then
            echo "✅ IPA file created successfully!"
            ls -la build/ios/ipa/*.ipa
          else
            echo "❌ IPA file not found"
            exit 1
          fi
          if [ -d "build/ios/archive" ] && [ "$(ls -A build/ios/archive/*.xcarchive 2>/dev/null)" ]; then
            echo "✅ Archive created successfully!"
            ls -la build/ios/archive/*.xcarchive
          else
            echo "❌ Archive not found"
            exit 1
          fi
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive.xcarchive
      - build/ios/xcodebuild.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
        beta_groups:
          - "Internal Testing"
      email:
        recipients:
          - info@cubstechnical.com
        notify:
          success: true
          failure: true

  ios-simulator-build:
    name: iOS Simulator Build (Dry Run)
    max_build_duration: 60
    environment:
      xcode: latest
      cocoapods: default
      node: 20.11.0
      vars:
        BUNDLE_ID: "com.cubstechnical.employee"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
    scripts:
      - name: Install Node.js dependencies
        script: |
          echo "📦 Installing Node.js dependencies..."
          npm ci
      - name: Build Next.js app
        script: |
          echo "🏗️ Building Next.js production app..."
          npm run build
      - name: Sync Capacitor iOS
        script: |
          echo "🔄 Syncing web assets with Capacitor iOS..."
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          echo "📱 Installing CocoaPods dependencies..."
          cd ios/App
          pod install
          cd ../..
      - name: Build for simulator (unsigned)
        script: |
          echo "📱 Building for iOS Simulator (unsigned)..."
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -destination 'platform=iOS Simulator,name=iPhone 14' \
            -derivedDataPath build/DerivedData \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_ALLOWED=NO \
            build
          cd ../..
      - name: Verify build
        script: |
          echo "✅ Verifying iOS simulator build..."
          if [ -d "ios/App/build/DerivedData/Build/Products/Release-iphonesimulator" ]; then
            echo "✅ iOS simulator build successful!"
            ls -la ios/App/build/DerivedData/Build/Products/Release-iphonesimulator/
          else
            echo "❌ iOS simulator build failed"
            exit 1
          fi
    artifacts:
      - ios/App/build/DerivedData/Build/Products/Release-iphonesimulator/*.app
    publishing:
      email:
        recipients:
          - info@cubstechnical.com
        notify:
          success: true
          failure: true

  android-build:
    name: Android Build
    max_build_duration: 60
    environment:
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.cubstechnical.admin"
    scripts:
      - name: Set up environment
        script: |
          echo "🔧 Setting up Android build environment..."
          export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
          export ANDROID_HOME=$HOME/Android/Sdk
          export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
      - name: Install dependencies
        script: |
          echo "📦 Installing Node.js dependencies..."
          npm ci
      - name: Build Next.js app
        script: |
          echo "🏗️ Building Next.js production app..."
          npm run build
      - name: Sync Capacitor Android
        script: |
          echo "🔄 Syncing web assets with Capacitor Android..."
          npx cap sync android
      - name: Build Android APK
        script: |
          echo "📱 Building Android APK..."
          cd android
          ./gradlew assembleDebug
          ./gradlew assembleRelease
          cd ..
      - name: Build Android AAB
        script: |
          echo "📦 Building Android App Bundle..."
          cd android
          ./gradlew bundleRelease
          cd ..
      - name: List build artifacts
        script: |
          echo "📋 Android build artifacts:"
          find android/app/build/outputs -name "*.apk" -o -name "*.aab" | head -10
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/bundle/release/*.aab
    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
      email:
        recipients:
          - info@cubstechnical.com
        notify:
          success: true
          failure: true