import { defineConfig, devices } from '@playwright/test';
import dotenv from 'dotenv';
import path from 'path';
import fs from 'fs';

// Load environment variables from .env file
dotenv.config({ path: path.resolve(__dirname, '.env') });

// Path to auth storage state (generated by npm run screenshots:login)
const AUTH_STORAGE_PATH = path.join(__dirname, 'app-store-assets', 'storageState.json');
const hasAuthState = fs.existsSync(AUTH_STORAGE_PATH);

/**
 * @see https://playwright.dev/docs/test-configuration
 */
export default defineConfig({
  testDir: './tests/e2e',
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: [
    ['html'],
    ['json', { outputFile: 'test-results/results.json' }]
  ],
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    baseURL: 'http://localhost:3000',

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',

    /* Take screenshot only when test fails */
    screenshot: 'only-on-failure',

    /* Record video only when test fails */
    video: 'retain-on-failure',
  },

  /* Configure projects for major browsers */
  projects: [
    // ======= UNAUTHENTICATED TESTS =======
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
      testMatch: ['**/smoke.spec.ts', '**/debug-network.spec.ts'],
    },

    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
      testMatch: ['**/smoke.spec.ts'],
    },

    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
      testMatch: ['**/smoke.spec.ts'],
    },

    /* Test against mobile viewports. */
    {
      name: 'Mobile Chrome',
      use: { ...devices['Pixel 5'] },
      testMatch: ['**/smoke.spec.ts'],
    },
    {
      name: 'Mobile Safari',
      use: { ...devices['iPhone 12'] },
      testMatch: ['**/smoke.spec.ts'],
    },

    // ======= AUTHENTICATED TESTS =======
    // These tests use saved auth state from: npm run screenshots:login
    ...(hasAuthState ? [
      {
        name: 'chromium-authenticated',
        use: {
          ...devices['Desktop Chrome'],
          storageState: AUTH_STORAGE_PATH,
        },
        testMatch: ['**/authenticated/**/*.spec.ts', '**/core-flow.spec.ts'],
      },
      {
        name: 'mobile-authenticated',
        use: {
          ...devices['iPhone 12'],
          storageState: AUTH_STORAGE_PATH,
        },
        testMatch: ['**/authenticated/**/*.spec.ts'],
      },
    ] : []),
  ],

  /* Run your local dev server before starting the tests */
  webServer: {
    command: 'echo "Using existing server"',
    url: 'http://localhost:3000',
    reuseExistingServer: true,
    timeout: 5000,
  },
});

